### ISSUE TITLE
Not honoring .flake8; error on setting global-config

### ISSUE THREAD

**Issue by ZaxR** [pre-commit/mirrors-autopep8#2]
Hi there. I'm having some trouble getting my config file to be honored.

With my `.pre-commit-config.yaml` set up as follows:

```
repos:
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.4
    hooks:
    -   id: autopep8
```
and a `.flake8` file as follows:

```
[flake8]
exclude=.git,__pycache__,docs/conf.py,build,dist
```

running `pre-commit run --all-files` ignores my .flake8.

I tried explicitly setting the file by modifying the `.pre-commit-config.yaml` file to read:
```
repos:
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.4
    hooks:
    -   id: autopep8
         args: [--global-config, .flake8]
```
but then I receive the following error:

> autopep8: error: autopep8 only takes one filename as argument unless the "--in-place" or "--diff" args are used

Other info: 

- File Tree:
```
.
├── project
│   ├── ...
├── docs
│   ├── ...
│   └── conf.py
├── .flake8
├── .pre-commit-config.yaml
├── setup.cfg
├── setup.py
└── tox.ini
```
- My pre-commit version is 1.18.2.

However, when I just try to commit having run `pre-commit install` in advance, the flake8 file is honored (either with or without the args).

How can I pass through my config for autopep8 when using `pre-commit run --all-files`? Thank you in advance!

I've asked this question on stackoverflow as well, but haven't received a response yet: https://stackoverflow.com/q/57582726/7619676
