### ISSUE TITLE
Cannot pass max-line-length argument directly in config file

### ISSUE THREAD

**Issue by Wattabak** [pre-commit/mirrors-autopep8#3]
When I pass the max line length argument to the config directly it produces an error, not sure what I am missing

.pre-commit.config.yaml: 

```
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.1
    hooks:
      - id: autopep8
        args: [ --max-line-length=120]
```

Error:

```
autopep8: error: autopep8 only takes one filename as argument unless the "--in-place" or "--diff" args are used
usage: autopep8
       [-h]
       [--version]
       [-v]
       [-d]
       [-i]
       [--global-config filename]
       [--ignore-local-config]
       [-r]
       [-j n]
       [-p n]
       [-a]
       [--experimental]
       [--exclude globs]
       [--list-fixes]
       [--ignore errors]
       [--select errors]
       [--max-line-length n]
       [--line-range line line]
       [--hang-closing]
       [--exit-code]
       [files [files ...]]
autopep8: error: autopep8 only takes one filename as argument unless the "--in-place" or "--diff" args are used

````
