### ISSUE TITLE
pep8 config file &/ overwriting args not working

### ISSUE THREAD

**Issue by jp185357** [pre-commit/mirrors-autopep8#5]
I'm trying to customize the rules for autopep8 and have tried overriding the args as well as using a pep8 config file per their mentioning in the readme but am not having any luck. When i change the args using the format:
```
- repo: https://github.com/pre-commit/mirrors-autopep8
    rev: master
    hooks:
      - id: autopep8
        args: [-d, -r, --list-fixes]
```
autopep8 does not catch any errors. However if i remove the `args:` line all-together, autopep8 appropriately runs as set to by default.

And because the args are not working I am unable to specify a config file for autopep8 to operate by.

Can you provide any insight as to how to override the args?
